name: Create release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Create a GitHub release
        uses: ncipollo/release-action@a5996b3a733af99dce9d614dc1d70412e81735c7
        with:
          tag: ${{ github.event.inputs.TAG_NAME }}
          name: Release ${{ github.event.inputs.TAG_NAME }}
          generateReleaseNotes: true
